web/accounts/urls.py
import email
from django import template
from django.shortcuts import render
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from .forms import CustomSetPasswordForm
from .views import register_user, login_user, logout_user, profile_user, delete_account_user

app_name = 'accounts'

urlpatterns = [
    path('register/', register_user, name='register'),
    path('email-verification-sent/', lambda request: render(request, 'accounts/email/email-verification-sent.html'), name='email-verification-sent'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('profile/', profile_user, name='profile'),
    path('delete-account/', delete_account_user, name='delete-account-user'),
    #ResetPassword
    path('reset-password/', auth_views.PasswordResetView.as_view(
        template_name='accounts/password/password-reset.html',
        email_template_name='accounts/password/password-reset-email.html',
        success_url=reverse_lazy('accounts:password-reset-done')
    ), name='password-reset'),
    path('reset-password/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password/password-reset-done.html'
    ), name='password-reset-done'),
    path('reset-password/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        form_class=CustomSetPasswordForm,
        template_name='accounts/password/password-reset-confirm.html',
        success_url=reverse_lazy('accounts:password-reset-complete')
    ), name='password-reset-confirm'),
    path('reset-password/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password/password-reset-complete.html'
    ), name='password-reset-complete'),
]

web/petmailing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import index
from django_email_verification import urls as email_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reminders/', include('reminders.urls', namespace='reminders')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('email/', include(email_urls), name='email-verification'),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('', index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/reminders/urls.py
from django.urls import path
from .views import reminders_home, ReminderContact, reminders_details, reminders_details_update, reminders_details_delete

app_name = 'reminders'

urlpatterns = [
    path('', reminders_home, name='reminders-home'),
    path('add/', ReminderContact.as_view(), name='reminders-add'),
    path('<slug:slug>/', reminders_details, name='reminders-details'),
    path('<slug:slug>/update/', reminders_details_update, name='reminders-details-update'),
    path('<slug:slug>/delete/', reminders_details_delete, name='reminders-details-delete'),
]

web/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task Planner - Главная</title>
    <link rel="stylesheet" href="{% static 'petmailing/css/home.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/css/profile.css' %}">
    {% block style %}
    {% endblock style %}
</head>
<body>
    <div class='wrapper'>
        <!-- Хэдер -->
        <header>
            <nav>
                <a href="{% url 'reminders:reminders-home' %}"><h1>Task Planner</h1></a>
                <ul>
                    <li>
                        <a href="{% url 'accounts:profile' %}">
                            <img src="{% static 'petmailing/images/account.png' %}" alt="Выйти" class="account-icon">
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:logout' %}">
                            <img src="{% static 'petmailing/images/exit.png' %}" alt="Выйти" class="exit-icon">
                        </a>
                    </li>
                </ul>
            </nav>
        </header>
        {% if messages %}
            <div class="container mt-3">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        <main>{% block content %}{% endblock content %}</main>
            <!-- Футер -->
        <footer>
            <p>&copy; {{ current_year }} Task Planner. Все права защищены.</p>
        </footer>
    </div>
</body>
</html>

web/templates/index.html
{% load static %}


<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task Planner - Планирование задач</title>
    <link rel="stylesheet" href="{% static 'petmailing/css/index.css' %}">
</head>
<body>
    <div class="welcome-container">
        <h1>Добро пожаловать в Task Planner!</h1>
        <p>Task Planner – это ваш личный помощник для планирования дел и задач. Здесь вы можете создавать свои ежедневные и недельные задачи, устанавливать напоминания и получать их вовремя на указанную при регистрации почту.</p>
        <p>Добавьте свои цели и планы в Task Planner, и мы позаботимся о том, чтобы вы не забыли о них – напоминания придут на вашу почту в нужное время.</p>
        
        <div class="button-group">
            <a href="{% url 'accounts:register' %}" class="btn btn-primary">Регистрация</a>
            <p class="button-label">Нет аккаунта? Зарегистрируйтесь!</p>
            
            <a href="{% url 'accounts:login' %}" class="btn btn-secondary">Вход</a>
            <p class="button-label">Уже есть аккаунт? Войдите!</p>
        </div>
    </div>
</body>
</html>