web/accounts/urls.py
import email
from django import template
from django.shortcuts import render
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from .forms import CustomSetPasswordForm
from .views import register_user, login_user, logout_user, profile_user, delete_account_user

app_name = 'accounts'

urlpatterns = [
    path('register/', register_user, name='register'),
    path('email-verification-sent/', lambda request: render(request, 'accounts/email/email-verification-sent.html'), name='email-verification-sent'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('profile/', profile_user, name='profile'),
    path('delete-account/', delete_account_user, name='delete-account-user'),
    #ResetPassword
    path('reset-password/', auth_views.PasswordResetView.as_view(
        template_name='accounts/password/password-reset.html',
        email_template_name='accounts/password/password-reset-email.html',
        success_url=reverse_lazy('accounts:password-reset-done')
    ), name='password-reset'),
    path('reset-password/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password/password-reset-done.html'
    ), name='password-reset-done'),
    path('reset-password/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        form_class=CustomSetPasswordForm,
        template_name='accounts/password/password-reset-confirm.html',
        success_url=reverse_lazy('accounts:password-reset-complete')
    ), name='password-reset-confirm'),
    path('reset-password/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password/password-reset-complete.html'
    ), name='password-reset-complete'),
]

web/petmailing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import index
from django_email_verification import urls as email_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reminders/', include('reminders.urls', namespace='reminders')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('email/', include(email_urls), name='email-verification'),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('', index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/accounts/models.py
from django.db import models

# Create your models here.

web/accounts/forms.py
from typing import Any
from django import forms
from django.forms import PasswordInput, TextInput
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, SetPasswordForm
from django.contrib.auth import get_user_model

User = get_user_model()

class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super(RegistrationForm, self).__init__(*args, **kwargs)
        
        self.fields['email'].label = 'Введите ваш email'
        self.fields['email'].required = True
        self.fields['username'].help_text = ''
        self.fields['username'].label = 'Имя пользователя'
        self.fields['password1'].label = 'Введите пароль'
        self.fields['password1'].help_text = ''
        self.fields['password2'].label = 'Подтвердите пароль'
        self.fields['password2'].help_text = ''
        
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        
        if len(email) > 254:
            raise forms.ValidationError("Почта слишком длинная.")
        
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Пользователь с такой почтой уже существует.")
        
        return email
    
#custom form for reset password
class CustomSetPasswordForm(SetPasswordForm):
    error_messages = {
        'password_mismatch': "Пароли не совпадают. Пожалуйста, попробуйте еще раз.",
        'password_too_similar': "Пароль не должен быть похож на личную информацию.",
        'password_too_short': "Пароль должен содержать не менее 8 символов.",
        'password_too_common': "Пароль слишком распространен, выберите другой.",
        'password_entirely_numeric': "Пароль не может состоять только из цифр.",
    }
    new_password1 = forms.CharField(
        label=("Новый пароль"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", "class": "form-control",}),
        strip=False,
    )
    new_password2 = forms.CharField(
        label=("Подтвердите новый пароль"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password","class": "form-control",}),
    )
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['new_password1'].help_text = '' 
        self.fields['new_password2'].help_text = ''

            
class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите имя пользователя'}))
    password = forms.CharField(widget=PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Введите пароль'}))
    
class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    
    def __init__(self, *args, **kwargs):
        super(UserUpdateForm,self).__init__(*args, **kwargs)
        
        self.fields['email'].label = 'Ваша Электронная почта'
        self.fields['email'].required = True
        
    class Meta:
        model = User
        fields = ['username', 'email']
        exclude = ('password1','password2')
            
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        
        if len(email) > 254:
            raise forms.ValidationError("Почта слишком длинная.")
        
        if User.objects.filter(email=email).exclude(id=self.instance.id).exists():
            raise forms.ValidationError("Пользователь с такой почтой уже существует.")
        
        return email

web/accounts/views.py
from asyncio import log
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.auth.decorators import login_required
from django_email_verification import send_email, send_password, verify_email_view
from django.contrib import messages

User = get_user_model()

from .forms import RegistrationForm, LoginForm, UserUpdateForm

def register_user(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        
        if form.is_valid():
            user = form.save(commit=False)
            user_email = form.cleaned_data.get('email')
            user_username = form.cleaned_data.get('username')
            user_password = form.cleaned_data.get('password1')
            
            user = User.objects.create_user(
                username=user_username, 
                email=user_email, 
                password=user_password
            )   
            user.is_active = False
            
            send_email(user)
            
            return redirect('/accounts/email-verification-sent/')
    else:
        form = RegistrationForm()
    return render(request, 'accounts/registration/register.html', {'form': form})
 

def login_user(request):
    form = LoginForm()
    
    if request.user.is_authenticated:
        return redirect('reminders:reminders-home')

    if request.method == 'POST':
        form = LoginForm(request.POST)
        
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(request, username=username, password=password)
        
        if request.user is not None:
            login(request, user)
            return redirect('reminders:reminders-home')
        else:
            messages.info(request, 'Неправильное имя пользователя или пароль')
            return redirect('accounts:login')
        
    context = {'form': form}
    return render(request, 'accounts/login/login.html', context)

def logout_user(request):
    logout(request)
    return redirect('index')


@login_required(login_url='accounts:login')
def profile_user(request):
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile')
        
    else:
        form = UserUpdateForm(instance=request.user)
    
    context = {'form': form}
    return render(request, 'accounts/profile/profile.html', context)

@login_required(login_url='accounts:login')
def delete_account_user(request):
    user = User.objects.get(id=request.user.id)
    if request.method == 'POST':
        user.delete()
        return redirect('index')
    return render(request, 'accounts/profile/delete-account-user.html')

web/templates/accounts/password/password-reset-complete.html
{%  extends "base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="success-message-container">
        <h3>Ваш пароль был успешно сброшен!</h3>

        <a href="{% url 'accounts:login' %}"> 
            <button class="btn btn-primary">
                Вернуться на страницу входа
            </button>
        </a>
    </div>

{% endblock content %}

web/templates/accounts/password/password-reset-confirm.html
{%  extends "base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}

    <br>
    <div class="container bg-white shadow-md p-5 form-layout">
        <h3>Введите новый пароль</h3>
        <br>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Изменить пароль</button>
        </form>

    </div>

{% endblock content %}

web/templates/accounts/password/password-reset-done.html
{%  extends "base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}

    <div class='notification-container'>
        <p>
            Ваш пароль был успешно отправлен!
            Пожалуйста, проверьте свою электронную почту для получения дальнейших инструкций.
        </p>
    </div>
{% endblock content %}

web/templates/accounts/password/password-reset-email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}Вы получили это электронное письмо, потому что запросили сброс пароля для своей учетной записи пользователя по адресу {{ site_name }}.{% endblocktranslate %}

{% translate "Пожалуйста, перейдите на следующую страницу и выберите новый пароль:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password-reset-confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Ваше имя пользователя, на случай, если вы забыли:' %} {{ user.get_username }}

{% translate "Спасибо за использование моего сайта!" %}

{% blocktranslate %}{{ site_name }}{% endblocktranslate %}

{% endautoescape %}

web/templates/accounts/password/password-reset.html
{%  extends "base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container bg-white shadow-md p-3 form-layout">
    <h3>Сброс пароля</h3>
    <br>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Сбросить пароль</button>
    </form>
</div>

{% endblock content %}