web/accounts/urls.py
import email
from django import template
from django.shortcuts import render
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from .forms import CustomSetPasswordForm
from .views import register_user, login_user, logout_user, profile_user, delete_account_user

app_name = 'accounts'

urlpatterns = [
    path('register/', register_user, name='register'),
    path('email-verification-sent/', lambda request: render(request, 'accounts/email/email-verification-sent.html'), name='email-verification-sent'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('profile/', profile_user, name='profile'),
    path('delete-account/', delete_account_user, name='delete-account-user'),
    #ResetPassword
    path('reset-password/', auth_views.PasswordResetView.as_view(
        template_name='accounts/password/password-reset.html',
        email_template_name='accounts/password/password-reset-email.html',
        success_url=reverse_lazy('accounts:password-reset-done')
    ), name='password-reset'),
    path('reset-password/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password/password-reset-done.html'
    ), name='password-reset-done'),
    path('reset-password/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        form_class=CustomSetPasswordForm,
        template_name='accounts/password/password-reset-confirm.html',
        success_url=reverse_lazy('accounts:password-reset-complete')
    ), name='password-reset-confirm'),
    path('reset-password/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password/password-reset-complete.html'
    ), name='password-reset-complete'),
]

web/petmailing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import index
from django_email_verification import urls as email_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reminders/', include('reminders.urls', namespace='reminders')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('email/', include(email_urls), name='email-verification'),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('', index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/reminders/urls.py
from django.urls import path
from .views import reminders_home, ReminderContact, reminders_details, reminders_details_update, reminders_details_delete

app_name = 'reminders'

urlpatterns = [
    path('', reminders_home, name='reminders-home'),
    path('add/', ReminderContact.as_view(), name='reminders-add'),
    path('<slug:slug>/', reminders_details, name='reminders-details'),
    path('<slug:slug>/update/', reminders_details_update, name='reminders-details-update'),
    path('<slug:slug>/delete/', reminders_details_delete, name='reminders-details-delete'),
]

web/reminders/models.py
import random
import string

from django.db import models
from django.contrib.auth import get_user_model
from django.utils.text import slugify

User = get_user_model()

class Reminder(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=500,blank=True, null=True)
    is_completed = models.BooleanField(default=False)
    date = models.DateTimeField()
    repeat_interval = models.CharField(max_length=20, 
                                       choices=[('daily', 'Ежедневно'),
                                                ('weekly', 'Еженедельно'),
                                                ('monthly', 'Ежемесячно'),
                                                ('none', 'Не повторять')], default='none')
    notification_time = models.DurationField(null=True, blank=True, 
                                             help_text='За сколько времени до события отправлять напоминание (например, 1 час или 30 минут)')
    slug = models.SlugField('URL', max_length=250, unique=True, blank=True)
    
    class Meta:
        verbose_name = 'Напоминание'
        verbose_name_plural = 'Напоминания'
    
    def __str__(self):
        return self.title
    
    @staticmethod
    def _rand_slug():
        return ''.join(random.choice(string.ascii_lowercase + string.digits) for _ in range(3))
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self._rand_slug() + '-' + self.title)
        super().save(*args, **kwargs)
        

web/reminders/forms.py
import datetime
from django import forms
from .models import Reminder
from django.utils import timezone

class AddReminderForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 2}))
    date = forms.DateTimeField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'datetime-local'}))
    repeat_interval = forms.ChoiceField(choices=[('none', 'Не повторять'),
                                                 ('daily', 'Ежедневно'),
                                                ('weekly', 'Еженедельно'),
                                                ('monthly', 'Ежемесячно'),
                                                ],
                                        widget=forms.Select(attrs={'class': 'form-control'}))
    notification_time = forms.DurationField(required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите длительность (например, 1:00:00 для 1 часа)'}))
    class Meta:
        model = Reminder
        fields = ['title', 'description', 'date', 'repeat_interval', 'notification_time']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields['title'].label = 'Заголовок Напоминания'
        self.fields['description'].label = 'Описание Напоминания'
        self.fields['date'].label = 'Дата для Напоминания'
        self.fields['repeat_interval'].label = 'Интервал повтора'
        self.fields['notification_time'].label = 'За сколько времени до события отправлять напоминание'
        
    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 100:
            raise forms.ValidationError("Заголовок Напоминания слишком длинный.")
        return title    
    
    def clean_description(self):
        description = self.cleaned_data['description']
        if len(description) > 500:
            raise forms.ValidationError("Описание Напоминания слишком длинное.")
        return description
        
    def clean_date(self):
        date = self.cleaned_data['date']
        if date < timezone.now():
            raise forms.ValidationError("Дата Напоминания не может быть ранее, чем сегодня.")
        return date
    
    
class UpdateReminderForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 2}))
    date = forms.DateTimeField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'datetime-local'}))
    repeat_interval = forms.ChoiceField(choices=[('none', 'Не повторять'),
                                                 ('daily', 'Ежедневно'),
                                                ('weekly', 'Еженедельно'),
                                                ('monthly', 'Ежемесячно'),
                                                ],
                                        widget=forms.Select(attrs={'class': 'form-control'}))
    notification_time = forms.DurationField(required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите длительность (например, 1:00:00 для 1 часа)'}))
    class Meta:
        model = Reminder
        fields = ['title', 'description', 'date', 'repeat_interval', 'notification_time']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields['title'].label = 'Заголовок Напоминания'
        self.fields['description'].label = 'Описание Напоминания'
        self.fields['date'].label = 'Дата для Напоминания'
        self.fields['repeat_interval'].label = 'Интервал повтора'
        self.fields['notification_time'].label = 'За сколько времени до события отправлять напоминание'
        
    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 100:
            raise forms.ValidationError("Заголовок Напоминания слишком длинный.")
        return title    
    
    def clean_description(self):
        description = self.cleaned_data['description']
        if len(description) > 500:
            raise forms.ValidationError("Описание Напоминания слишком длинное.")
        return description
        
    def clean_date(self):
        date = self.cleaned_data['date']
        if date < timezone.now():
            raise forms.ValidationError("Дата Напоминания не может быть ранее, чем сегодня.")
        return date

web/reminders/views.py
from asyncio import log
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import CreateView
from django.contrib import messages
from datetime import datetime
from .models import Reminder
from .forms import AddReminderForm, UpdateReminderForm
from .tasks import send_reminder_email

@login_required(login_url='accounts:login')
def reminders_home(request):
    reminders = Reminder.objects.all().filter(user_id=request.user)
    active_reminders = Reminder.objects.all().filter(user_id=request.user, is_completed=False)
    completed_reminders = Reminder.objects.all().filter(user_id=request.user, is_completed=True)    
    current_year = datetime.now().year
    context = {
        'reminders': reminders, 
        'active_reminders': active_reminders,
        'completed_reminders': completed_reminders,
        'current_year': current_year
        }
    return render(request, 'reminders/reminders-home.html', context)

@login_required(login_url='accounts:login')
def form_valid(self, form):
    messages.success(self.request, 'Напоминание успешно создано!')
    return super().form_valid(form)


class ReminderContact(LoginRequiredMixin, CreateView):
    model = Reminder
    form_class = AddReminderForm
    success_url = '/reminders/'
    template_name = 'reminders/reminders-add.html'

    def form_valid(self, form):
        reminder = form.save(commit=False)
        reminder.user_id = self.request.user
        reminder.save()
        
        if reminder.notification_time is not None: 
            notification_time = reminder.date - reminder.notification_time
            send_reminder_email.apply_async((reminder.id,), eta=notification_time)
        else:
            send_reminder_email.apply_async((reminder.id,), eta=reminder.date)
        return super().form_valid(form)

@login_required(login_url='accounts:login')
def reminders_details(request, slug):
    reminder = get_object_or_404(Reminder, slug=slug, user_id=request.user)
    reminder_repeat_interval = reminder.get_repeat_interval_display()
    
    if reminder.notification_time is not None:
        actual_send_time = reminder.date - reminder.notification_time
        context = {
            'reminder': reminder,
            'actual_send_time': actual_send_time,
            'reminder_repeat_interval': reminder_repeat_interval
        }
    else:
        context = {
            'reminder': reminder,
            'reminder_repeat_interval': reminder_repeat_interval
        }

    return render(request, 'reminders/reminders-details.html', context)

@login_required(login_url='accounts:login')
def reminders_details_update(request, slug):
    model = Reminder
    form = UpdateReminderForm
    reminder = get_object_or_404(Reminder, slug=slug, user_id=request.user)
    if request.method == 'POST':
        form = UpdateReminderForm(request.POST, instance=reminder)
        if form.is_valid():
            form.save()
            return redirect('reminders:reminders-details', slug=slug)
    else:
        form = UpdateReminderForm(instance=reminder)
    context = {'form': form,'reminder': reminder}
    return render(request, 'reminders/reminders-details-update.html', context)

@login_required(login_url='accounts:login')
def reminders_details_delete(request, slug):
    reminder = get_object_or_404(Reminder, slug=slug, user_id=request.user)
    if request.method == 'POST':
        reminder.delete()
        return redirect('reminders:reminders-home')
    return render(request, 'reminders/reminders-confirm-delete.html', {'reminder': reminder})

web/templates/reminders/reminders-add.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_tags %}

{% block style %}
<link rel="stylesheet" href="{% static 'reminders/css/reminders-add.css' %}">
{% endblock style %}

{% block content %}
<div class="container mt-5">
    <div class="card shadow-sm">
        <div class="card-header bg-primary text-white">
            <h4 class="mb-0">Добавить новое напоминание</h4>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success w-100">Создать напоминание</button>
                <a href="{% url 'reminders:reminders-home' %}" class="btn btn-primary mt-3">Назад к напоминаниям</a>
            </form>
            {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    {% for field in form %}
                        {% if field.errors %}
                            {{ field.errors }}
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

web/templates/reminders/reminders-confirm-delete.html
<!-- reminder_confirm_delete.html -->
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h2>Подтверждение удаления</h2>
    <p>Вы уверены, что хотите удалить напоминание "{{ reminder.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'reminders:reminders-home' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>

<style>
    .container {
        max-width: 600px; /* Укажите максимальную ширину контейнера */
        margin: 20px auto; /* Установите отступы сверху и снизу, и выровняйте по центру */
        padding: 20px; /* Добавьте внутренние отступы, если необходимо */
        background-color: #fff; /* Убедитесь, что фон установлен для визуального эффекта */
        border-radius: 8px; /* Углы контейнера будут скругленными */
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1); /* Тень для контейнера */
    }
</style>
{% endblock content %}

web/templates/reminders/reminders-details-update.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h2>Детали Напоминания</h2>

    <div class="reminder-details">
        <h3>{{ reminder.title }}</h3>
        <p><strong>Описание:</strong> {{ reminder.description }}</p>
        <p><strong>Дата Напоминания:</strong> {{ reminder.date }}</p>
        <p><strong>Статус:</strong> {{ reminder.is_completed|yesno:"Завершено,В процессе" }}</p>
    </div>

    <h3>Обновить Напоминание</h3>
    <div class="update-form">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Обновить Напоминание</button>
        </form>
    </div>

    <div class="actions mt-3">
        <a href="{% url 'reminders:reminders-home' %}" class="btn btn-secondary">Назад к Напоминаниям</a>
    </div>
</div>

<style>
    .container {
        max-width: 600px;
        margin: 20px auto; /* Центрирование контейнера и добавление отступа сверху */
        padding: 20px;
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    }

    h2 {
        text-align: center; /* Выравнивание заголовка по центру */
        margin-bottom: 20px; /* Отступ снизу */
    }

    .reminder-details {
        margin-bottom: 30px; /* Добавление отступа снизу */
        padding: 15px; /* Добавление внутреннего отступа */
        border: 1px solid #e0e0e0; /* Легкая граница для выделения */
        border-radius: 5px; /* Скругление углов */
        background-color: #f9f9f9; /* Светлый фон для деталей */
    }

    .reminder-details h3 {
        color: #4CAF50; /* Цвет заголовка */
        margin-bottom: 10px; /* Отступ снизу */
    }

    .update-form {
        margin-top: 20px; /* Отступ сверху */
    }

    .actions {
        margin-top: 30px; /* Отступ сверху */
        text-align: center; /* Центрирование кнопки */
    }

    .btn {
        display: inline-block; /* Делает кнопку блочным элементом */
        margin: 5px; /* Отступ вокруг кнопок */
    }
</style>
{% endblock content %}

web/templates/reminders/reminders-details.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="reminder-detail bg-white shadow-md p-4 rounded">
        <h2>{{ reminder.title }}</h2>
        <p><strong>Описание:</strong> {{ reminder.description }}</p>
        <p><strong>Дата для Напоминания:</strong> {{ reminder.date|date:"d.m.Y H:i" }}</p>
        <p><strong>Статус:</strong> {% if reminder.is_completed %} Завершено {% else %} В процессе {% endif %}</p>
        <p><strong>Интервал напоминания:</strong> {{ reminder_repeat_interval }}</p>
        <p><strong>Время отправки напоминания:</strong> {{ actual_send_time|date:"d F Y г. H:i" }}</p>
        
        <a href="{% url 'reminders:reminders-details-update' reminder.slug %}" class="btn btn-primary mt-3">Редактировать</a>
        <a href="{% url 'reminders:reminders-details-delete' reminder.slug %}" class="btn btn-primary mt-3">Удалить</a>
        <a href="{% url 'reminders:reminders-home' %}" class="btn btn-primary mt-3">Назад к напоминаниям</a>
    </div>
</div>

<style>
    .reminder-detail a{
        text-decoration: none;
    }
    .container {
        display: flex;
        justify-content: center;
        align-items: center;
    }
</style>
{% endblock content %}

web/templates/reminders/reminders-home.html
{% extends "base.html" %}

{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'reminders/css/reminders-home.css' %}">
{% endblock style %}


{% block content %}
<!-- Мэйн-контейнер -->
    <section class="kanban-board">
        {% if reminders.exists %}
            <section class="kanban-board">
                <div class="column">
                    <h2>Ваши Напоминания</h2>
                    {% for active in active_reminders %}
                        <a href="{% url 'reminders:reminders-details' active.slug %}">
                            <div class="reminder-card">
                                <p>{{ active.title }}</p>
                                <p>Дата: {{ active.date|date:"d.m.Y H:i" }}</p>
                            </div>
                        </a>
                    {% endfor %}
                    <a href="{% url 'reminders:reminders-add' %}" class="add-reminder-btn">Добавить напоминание</a>
                </div>
                
                <div class="column">
                    <h2>Завершенные напоминания</h2>
                    {% for completed in completed_reminders %}
                        <a href="{% url 'reminders:reminders-details' completed.slug %}">
                            <div class="reminder-card">
                                <p>{{ completed.title }}</p>
                                <p>Дата завершения: {{ completed.date|date:"d.m.Y H:i" }}</p>
                            </div>
                        </a>
                    {% endfor %}
                </div>
            </section>
        {% else %}
            <section class="empty-reminders">
                <h2>У вас еще нет напоминаний</h2>
                <a href="{% url 'reminders:reminders-add' %}" class="add-reminder-btn">Добавить напоминание</a>
            </section>
        {% endif %}
    </section>

{% endblock content %}